# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: ./.github/workflows/test.yaml
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 1
      #     ref: ${{github.event.pull_request.head.ref}}
      #     repository: ${{github.event.pull_request.head.repo.full_name}}
      #     submodules: recursive
      # - uses: ./.github/workflows/staging.yml
      #   with:
      #     branch_name: ${{ env.NAME }}
      # - uses: ./.github/workflows/test.yml